---
- name: Wait for any unattended upgrade to finish
  ansible.builtin.raw: |
    systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" \
                --wait /bin/true

# Some Google Cloud components don't like IPv6 ingress
- name: Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  with_items:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6
  - net.ipv6.conf.lo.disable_ipv6

- name: Blacklist IPv6 in modprobe
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/blacklist.conf
    line: "blacklist ipv6"
    mode: "0644"
    create: yes

- name: Install prerequisites
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - gnupg
    update_cache: yes

- name: Install toolchain from standard packages
  ansible.builtin.apt:
    pkg:
    - coreutils
    - expect
    - gawk
    - git
    - ipcalc
    - jq
    - make
    - mysql-client
    - postgresql-client
    - sed
    update_cache: yes

- name: Download the Google Cloud SDK package repository signing key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/gcloud.asc

- name: Add Google Cloud SDK package repository source
  ansible.builtin.apt_repository:
    filename: google-cloud-sdk.list
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/gcloud.asc] https://packages.cloud.google.com/apt cloud-sdk main"
    update_cache: yes

- name: Install Google Cloud toolchain
  ansible.builtin.apt:
    pkg:
    - google-cloud-sdk
    - kubectl
    update_cache: yes

- name: Create Google Cloud SDK directory structure
  ansible.builtin.file:
    path: ~/.config/gcloud/configurations
    state: directory
  become: no

- name: Write Google Cloud SDK "finngen" configuration
  ansible.builtin.template:
    src: config_finngen.j2
    dest: ~/.config/gcloud/configurations/config_finngen
  become: no

- name: Write Google Cloud SDK "docker" configuration
  ansible.builtin.template:
    src: config_docker.j2
    dest: ~/.config/gcloud/configurations/config_docker
  become: no

- name: Copy Google Cloud service account key for container registry
  ansible.builtin.copy:
    src: "{{ google.sa.container.key }}"
    dest: ~/.container-registry.key.json
    mode: "0600"
  become: no

# FIXME This is probably not idempotent
- name: Activate container registry service account and configure Docker
  ansible.builtin.shell: |
    gcloud config configurations activate docker
    gcloud auth activate-service-account {{ google.sa.container.account }}@{{ google.project.container }}.iam.gserviceaccount.com --key-file=/home/ubuntu/.container-registry.key.json
    gcloud auth configure-docker --quiet
  become: no

- name: Copy Docker pull-tag-push helper script
  ansible.builtin.template:
    src: docker-dance.sh.j2
    dest: ~/docker-dance.sh
    mode: "0700"
  become: no

- name: Checkout the TRE codebase
  ansible.builtin.git:
    repo: "https://{{ github.username | urlencode }}:{{ github.password | urlencode }}@github.com/wsi-hgi-tre/finngen-v3.git"
    version: "{{ tre.branch }}"
    dest: ~/finngen
    single_branch: yes
  become: no

- name: Copy Bash prompt helper script
  ansible.builtin.copy:
    src: .finngenrc
    dest: ~/.finngenrc
  become: no

- name: Enable Bash prompt helper
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "source ~/.finngenrc"
  become: no

- name: Set environment variables
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "export {{ item.key }}={{ item.value }}"
  become: no
  loop: "{{ query('dict', tre.environment | default({})) }}"
